// This file was generated by Claude from prompts/spec.md.
// It is a reference example — your Claude output may differ slightly.
import { test, expect } from '@playwright/test';

test.beforeEach(async ({ page }) => {
  await page.goto('/shop/');
  await page.waitForLoadState('networkidle');
});

test('shop page loads with a visible product grid', async ({ page }) => {
  // WooCommerce product grids use .products or ul.products
  const grid = page.locator('.products, ul.products');
  await expect(grid.first()).toBeVisible();
});

test('at least one product is visible', async ({ page }) => {
  const products = page.locator('li.product, .type-product');
  const count = await products.count();
  expect(count).toBeGreaterThan(0);
});

test('first product card shows a non-empty name', async ({ page }) => {
  const firstName = page.locator('.woocommerce-loop-product__title').first();
  await expect(firstName).toBeVisible();
  const text = await firstName.textContent();
  expect(text?.trim().length).toBeGreaterThan(0);
});

test('first product card shows a price with currency symbol', async ({ page }) => {
  const price = page.locator('.price').first();
  await expect(price).toBeVisible();
  await expect(price).toContainText(/[$£€]/);
});

test('clicking first product name goes to product detail page', async ({ page }) => {
  const firstName = page.locator('.woocommerce-loop-product__title').first();
  const productName = (await firstName.textContent())?.trim() ?? '';
  await firstName.click();
  await page.waitForLoadState('networkidle');
  await expect(page.locator('h1.product_title')).toContainText(productName);
});

test('product detail page has an Add to Cart button', async ({ page }) => {
  await page.locator('.woocommerce-loop-product__title').first().click();
  await page.waitForLoadState('networkidle');
  await expect(page.locator('.single_add_to_cart_button')).toBeVisible();
});
